<?php

/**
 * 		
 */
class Icons
{
	
	function __construct()
	{
		# code...
	}

	public function get($value='', $html = false)
	{
		switch ($value) {
			case 'feather':
				return $this->feather($html);
				break;
			
			default:
				# code...
				break;
		}
	}

	private function feather($html)
	{
		$icons = [
				    [
				        ""
				    ],
				    [
				        "icon-alert-octagon",
				        "&#xe81b"
				    ],
				    [
				        "icon-alert-circle",
				        "&#xe81c"
				    ],
				    [
				        "icon-activity",
				        "&#xe81d"
				    ],
				    [
				        "icon-alert-triangle",
				        "&#xe81e"
				    ],
				    [
				        "icon-align-center",
				        "&#xe81f"
				    ],
				    [
				        "icon-airplay",
				        "&#xe820"
				    ],
				    [
				        "icon-align-justify",
				        "&#xe821"
				    ],
				    [
				        "icon-align-left",
				        "&#xe822"
				    ],
				    [
				        "icon-align-right",
				        "&#xe823"
				    ],
				    [
				        "icon-arrow-down-left",
				        "&#xe824"
				    ],
				    [
				        "icon-arrow-down-right",
				        "&#xe825"
				    ],
				    [
				        "icon-anchor",
				        "&#xe826"
				    ],
				    [
				        "icon-aperture",
				        "&#xe827"
				    ],
				    [
				        "icon-arrow-left",
				        "&#xe828"
				    ],
				    [
				        "icon-arrow-right",
				        "&#xe829"
				    ],
				    [
				        "icon-arrow-down",
				        "&#xe82a"
				    ],
				    [
				        "icon-arrow-up-left",
				        "&#xe82b"
				    ],
				    [
				        "icon-arrow-up-right",
				        "&#xe82c"
				    ],
				    [
				        "icon-arrow-up",
				        "&#xe82d"
				    ],
				    [
				        "icon-award",
				        "&#xe82e"
				    ],
				    [
				        "icon-bar-chart",
				        "&#xe82f"
				    ],
				    [
				        "icon-at-sign",
				        "&#xe830"
				    ],
				    [
				        "icon-bar-chart-2",
				        "&#xe831"
				    ],
				    [
				        "icon-battery-charging",
				        "&#xe832"
				    ],
				    [
				        "icon-bell-off",
				        "&#xe833"
				    ],
				    [
				        "icon-battery",
				        "&#xe834"
				    ],
				    [
				        "icon-bluetooth",
				        "&#xe835"
				    ],
				    [
				        "icon-bell",
				        "&#xe836"
				    ],
				    [
				        "icon-book",
				        "&#xe837"
				    ],
				    [
				        "icon-briefcase",
				        "&#xe838"
				    ],
				    [
				        "icon-camera-off",
				        "&#xe839"
				    ],
				    [
				        "icon-calendar",
				        "&#xe83a"
				    ],
				    [
				        "icon-bookmark",
				        "&#xe83b"
				    ],
				    [
				        "icon-box",
				        "&#xe83c"
				    ],
				    [
				        "icon-camera",
				        "&#xe83d"
				    ],
				    [
				        "icon-check-circle",
				        "&#xe83e"
				    ],
				    [
				        "icon-check",
				        "&#xe83f"
				    ],
				    [
				        "icon-check-square",
				        "&#xe840"
				    ],
				    [
				        "icon-cast",
				        "&#xe841"
				    ],
				    [
				        "icon-chevron-down",
				        "&#xe842"
				    ],
				    [
				        "icon-chevron-left",
				        "&#xe843"
				    ],
				    [
				        "icon-chevron-right",
				        "&#xe844"
				    ],
				    [
				        "icon-chevron-up",
				        "&#xe845"
				    ],
				    [
				        "icon-chevrons-down",
				        "&#xe846"
				    ],
				    [
				        "icon-chevrons-right",
				        "&#xe847"
				    ],
				    [
				        "icon-chevrons-up",
				        "&#xe848"
				    ],
				    [
				        "icon-chevrons-left",
				        "&#xe849"
				    ],
				    [
				        "icon-circle",
				        "&#xe84a"
				    ],
				    [
				        "icon-clipboard",
				        "&#xe84b"
				    ],
				    [
				        "icon-chrome",
				        "&#xe84c"
				    ],
				    [
				        "icon-clock",
				        "&#xe84d"
				    ],
				    [
				        "icon-cloud-lightning",
				        "&#xe84e"
				    ],
				    [
				        "icon-cloud-drizzle",
				        "&#xe84f"
				    ],
				    [
				        "icon-cloud-rain",
				        "&#xe850"
				    ],
				    [
				        "icon-cloud-off",
				        "&#xe851"
				    ],
				    [
				        "icon-codepen",
				        "&#xe852"
				    ],
				    [
				        "icon-cloud-snow",
				        "&#xe853"
				    ],
				    [
				        "icon-compass",
				        "&#xe854"
				    ],
				    [
				        "icon-copy",
				        "&#xe855"
				    ],
				    [
				        "icon-corner-down-right",
				        "&#xe856"
				    ],
				    [
				        "icon-corner-down-left",
				        "&#xe857"
				    ],
				    [
				        "icon-corner-left-down",
				        "&#xe858"
				    ],
				    [
				        "icon-corner-left-up",
				        "&#xe859"
				    ],
				    [
				        "icon-corner-up-left",
				        "&#xe85a"
				    ],
				    [
				        "icon-corner-up-right",
				        "&#xe85b"
				    ],
				    [
				        "icon-corner-right-down",
				        "&#xe85c"
				    ],
				    [
				        "icon-corner-right-up",
				        "&#xe85d"
				    ],
				    [
				        "icon-cpu",
				        "&#xe85e"
				    ],
				    [
				        "icon-credit-card",
				        "&#xe85f"
				    ],
				    [
				        "icon-crosshair",
				        "&#xe860"
				    ],
				    [
				        "icon-disc",
				        "&#xe861"
				    ],
				    [
				        "icon-delete",
				        "&#xe862"
				    ],
				    [
				        "icon-download-cloud",
				        "&#xe863"
				    ],
				    [
				        "icon-download",
				        "&#xe864"
				    ],
				    [
				        "icon-droplet",
				        "&#xe865"
				    ],
				    [
				        "icon-edit-2",
				        "&#xe866"
				    ],
				    [
				        "icon-edit",
				        "&#xe867"
				    ],
				    [
				        "icon-edit-1",
				        "&#xe868"
				    ],
				    [
				        "icon-external-link",
				        "&#xe869"
				    ],
				    [
				        "icon-eye",
				        "&#xe86a"
				    ],
				    [
				        "icon-feather",
				        "&#xe86b"
				    ],
				    [
				        "icon-facebook",
				        "&#xe86c"
				    ],
				    [
				        "icon-file-minus",
				        "&#xe86d"
				    ],
				    [
				        "icon-eye-off",
				        "&#xe86e"
				    ],
				    [
				        "icon-fast-forward",
				        "&#xe86f"
				    ],
				    [
				        "icon-file-text",
				        "&#xe870"
				    ],
				    [
				        "icon-film",
				        "&#xe871"
				    ],
				    [
				        "icon-file",
				        "&#xe872"
				    ],
				    [
				        "icon-file-plus",
				        "&#xe873"
				    ],
				    [
				        "icon-folder",
				        "&#xe874"
				    ],
				    [
				        "icon-filter",
				        "&#xe875"
				    ],
				    [
				        "icon-flag",
				        "&#xe876"
				    ],
				    [
				        "icon-globe",
				        "&#xe877"
				    ],
				    [
				        "icon-grid",
				        "&#xe878"
				    ],
				    [
				        "icon-heart",
				        "&#xe879"
				    ],
				    [
				        "icon-home",
				        "&#xe87a"
				    ],
				    [
				        "icon-github",
				        "&#xe87b"
				    ],
				    [
				        "icon-image",
				        "&#xe87c"
				    ],
				    [
				        "icon-inbox",
				        "&#xe87d"
				    ],
				    [
				        "icon-layers",
				        "&#xe87e"
				    ],
				    [
				        "icon-info",
				        "&#xe87f"
				    ],
				    [
				        "icon-instagram",
				        "&#xe880"
				    ],
				    [
				        "icon-layout",
				        "&#xe881"
				    ],
				    [
				        "icon-link-2",
				        "&#xe882"
				    ],
				    [
				        "icon-life-buoy",
				        "&#xe883"
				    ],
				    [
				        "icon-link",
				        "&#xe884"
				    ],
				    [
				        "icon-log-in",
				        "&#xe885"
				    ],
				    [
				        "icon-list",
				        "&#xe886"
				    ],
				    [
				        "icon-lock",
				        "&#xe887"
				    ],
				    [
				        "icon-log-out",
				        "&#xe888"
				    ],
				    [
				        "icon-loader",
				        "&#xe889"
				    ],
				    [
				        "icon-mail",
				        "&#xe88a"
				    ],
				    [
				        "icon-maximize-2",
				        "&#xe88b"
				    ],
				    [
				        "icon-map",
				        "&#xe88c"
				    ],
				    [
				        "icon-map-pin",
				        "&#xe88e"
				    ],
				    [
				        "icon-menu",
				        "&#xe88f"
				    ],
				    [
				        "icon-message-circle",
				        "&#xe890"
				    ],
				    [
				        "icon-message-square",
				        "&#xe891"
				    ],
				    [
				        "icon-minimize-2",
				        "&#xe892"
				    ],
				    [
				        "icon-mic-off",
				        "&#xe893"
				    ],
				    [
				        "icon-minus-circle",
				        "&#xe894"
				    ],
				    [
				        "icon-mic",
				        "&#xe895"
				    ],
				    [
				        "icon-minus-square",
				        "&#xe896"
				    ],
				    [
				        "icon-minus",
				        "&#xe897"
				    ],
				    [
				        "icon-moon",
				        "&#xe898"
				    ],
				    [
				        "icon-monitor",
				        "&#xe899"
				    ],
				    [
				        "icon-more-vertical",
				        "&#xe89a"
				    ],
				    [
				        "icon-more-horizontal",
				        "&#xe89b"
				    ],
				    [
				        "icon-move",
				        "&#xe89c"
				    ],
				    [
				        "icon-music",
				        "&#xe89d"
				    ],
				    [
				        "icon-navigation-2",
				        "&#xe89e"
				    ],
				    [
				        "icon-navigation",
				        "&#xe89f"
				    ],
				    [
				        "icon-octagon",
				        "&#xe8a0"
				    ],
				    [
				        "icon-package",
				        "&#xe8a1"
				    ],
				    [
				        "icon-pause-circle",
				        "&#xe8a2"
				    ],
				    [
				        "icon-pause",
				        "&#xe8a3"
				    ],
				    [
				        "icon-percent",
				        "&#xe8a4"
				    ],
				    [
				        "icon-phone-call",
				        "&#xe8a5"
				    ],
				    [
				        "icon-phone-forwarded",
				        "&#xe8a6"
				    ],
				    [
				        "icon-phone-missed",
				        "&#xe8a7"
				    ],
				    [
				        "icon-phone-off",
				        "&#xe8a8"
				    ],
				    [
				        "icon-phone-incoming",
				        "&#xe8a9"
				    ],
				    [
				        "icon-phone",
				        "&#xe8aa"
				    ],
				    [
				        "icon-phone-outgoing",
				        "&#xe8ab"
				    ],
				    [
				        "icon-pie-chart",
				        "&#xe8ac"
				    ],
				    [
				        "icon-play-circle",
				        "&#xe8ad"
				    ],
				    [
				        "icon-play",
				        "&#xe8ae"
				    ],
				    [
				        "icon-plus-square",
				        "&#xe8af"
				    ],
				    [
				        "icon-plus-circle",
				        "&#xe8b0"
				    ],
				    [
				        "icon-plus",
				        "&#xe8b1"
				    ],
				    [
				        "icon-pocket",
				        "&#xe8b2"
				    ],
				    [
				        "icon-printer",
				        "&#xe8b3"
				    ],
				    [
				        "icon-power",
				        "&#xe8b4"
				    ],
				    [
				        "icon-radio",
				        "&#xe8b5"
				    ],
				    [
				        "icon-repeat",
				        "&#xe8b6"
				    ],
				    [
				        "icon-refresh-ccw",
				        "&#xe8b7"
				    ],
				    [
				        "icon-rewind",
				        "&#xe8b8"
				    ],
				    [
				        "icon-rotate-ccw",
				        "&#xe8b9"
				    ],
				    [
				        "icon-refresh-cw",
				        "&#xe8ba"
				    ],
				    [
				        "icon-rotate-cw",
				        "&#xe8bb"
				    ],
				    [
				        "icon-save",
				        "&#xe8bc"
				    ],
				    [
				        "icon-search",
				        "&#xe8bd"
				    ],
				    [
				        "icon-server",
				        "&#xe8be"
				    ],
				    [
				        "icon-scissors",
				        "&#xe8bf"
				    ],
				    [
				        "icon-share-2",
				        "&#xe8c0"
				    ],
				    [
				        "icon-share",
				        "&#xe8c1"
				    ],
				    [
				        "icon-shield",
				        "&#xe8c2"
				    ],
				    [
				        "icon-settings",
				        "&#xe8c3"
				    ],
				    [
				        "icon-skip-back",
				        "&#xe8c4"
				    ],
				    [
				        "icon-shuffle",
				        "&#xe8c5"
				    ],
				    [
				        "icon-sidebar",
				        "&#xe8c6"
				    ],
				    [
				        "icon-skip-forward",
				        "&#xe8c7"
				    ],
				    [
				        "icon-slack",
				        "&#xe8c8"
				    ],
				    [
				        "icon-slash",
				        "&#xe8c9"
				    ],
				    [
				        "icon-smartphone",
				        "&#xe8ca"
				    ],
				    [
				        "icon-square",
				        "&#xe8cb"
				    ],
				    [
				        "icon-speaker",
				        "&#xe8cc"
				    ],
				    [
				        "icon-star",
				        "&#xe8cd"
				    ],
				    [
				        "icon-stop-circle",
				        "&#xe8ce"
				    ],
				    [
				        "icon-sun",
				        "&#xe8cf"
				    ],
				    [
				        "icon-sunrise",
				        "&#xe8d0"
				    ],
				    [
				        "icon-tablet",
				        "&#xe8d1"
				    ],
				    [
				        "icon-tag",
				        "&#xe8d2"
				    ],
				    [
				        "icon-sunset",
				        "&#xe8d3"
				    ],
				    [
				        "icon-target",
				        "&#xe8d4"
				    ],
				    [
				        "icon-thermometer",
				        "&#xe8d5"
				    ],
				    [
				        "icon-thumbs-up",
				        "&#xe8d6"
				    ],
				    [
				        "icon-thumbs-down",
				        "&#xe8d7"
				    ],
				    [
				        "icon-toggle-left",
				        "&#xe8d8"
				    ],
				    [
				        "icon-toggle-right",
				        "&#xe8d9"
				    ],
				    [
				        "icon-trash-2",
				        "&#xe8da"
				    ],
				    [
				        "icon-trash",
				        "&#xe8db"
				    ],
				    [
				        "icon-trending-up",
				        "&#xe8dc"
				    ],
				    [
				        "icon-trending-down",
				        "&#xe8dd"
				    ],
				    [
				        "icon-triangle",
				        "&#xe8de"
				    ],
				    [
				        "icon-type",
				        "&#xe8df"
				    ],
				    [
				        "icon-twitter",
				        "&#xe8e0"
				    ],
				    [
				        "icon-upload",
				        "&#xe8e1"
				    ],
				    [
				        "icon-umbrella",
				        "&#xe8e2"
				    ],
				    [
				        "icon-upload-cloud",
				        "&#xe8e3"
				    ],
				    [
				        "icon-unlock",
				        "&#xe8e4"
				    ],
				    [
				        "icon-user-check",
				        "&#xe8e5"
				    ],
				    [
				        "icon-user-minus",
				        "&#xe8e6"
				    ],
				    [
				        "icon-user-plus",
				        "&#xe8e7"
				    ],
				    [
				        "icon-user-x",
				        "&#xe8e8"
				    ],
				    [
				        "icon-user",
				        "&#xe8e9"
				    ],
				    [
				        "icon-users",
				        "&#xe8ea"
				    ],
				    [
				        "icon-video-off",
				        "&#xe8eb"
				    ],
				    [
				        "icon-video",
				        "&#xe8ec"
				    ],
				    [
				        "icon-voicemail",
				        "&#xe8ed"
				    ],
				    [
				        "icon-volume-x",
				        "&#xe8ee"
				    ],
				    [
				        "icon-volume-2",
				        "&#xe8ef"
				    ],
				    [
				        "icon-volume-1",
				        "&#xe8f0"
				    ],
				    [
				        "icon-volume",
				        "&#xe8f1"
				    ],
				    [
				        "icon-watch",
				        "&#xe8f2"
				    ],
				    [
				        "icon-wifi",
				        "&#xe8f3"
				    ],
				    [
				        "icon-x-square",
				        "&#xe8f4"
				    ],
				    [
				        "icon-wind",
				        "&#xe8f5"
				    ],
				    [
				        "icon-x",
				        "&#xe8f6"
				    ],
				    [
				        "icon-x-circle",
				        "&#xe8f7"
				    ],
				    [
				        "icon-zap",
				        "&#xe8f8"
				    ],
				    [
				        "icon-zoom-in",
				        "&#xe8f9"
				    ],
				    [
				        "icon-zoom-out",
				        "&#xe8fa"
				    ],
				    [
				        "icon-command",
				        "&#xe8fb"
				    ],
				    [
				        "icon-cloud",
				        "&#xe8fc"
				    ],
				    [
				        "icon-hash",
				        "&#xe8fd"
				    ],
				    [
				        "icon-headphones",
				        "&#xe8fe"
				    ],
				    [
				        "icon-underline",
				        "&#xe8ff"
				    ],
				    [
				        "icon-italic",
				        "&#xe900"
				    ],
				    [
				        "icon-bold",
				        "&#xe901"
				    ],
				    [
				        "icon-crop",
				        "&#xe902"
				    ],
				    [
				        "icon-help-circle",
				        "&#xe903"
				    ],
				    [
				        "icon-paperclip",
				        "&#xe904"
				    ],
				    [
				        "icon-shopping-cart",
				        "&#xe905"
				    ],
				    [
				        "icon-tv",
				        "&#xe906"
				    ],
				    [
				        "icon-wifi-off",
				        "&#xe907"
				    ],
				    [
				        "icon-minimize",
				        "&#xe88d"
				    ],
				    [
				        "icon-maximize",
				        "&#xe908"
				    ],
				    [
				        "icon-gitlab",
				        "&#xe909"
				    ],
				    [
				        "icon-sliders",
				        "&#xe90a"
				    ],
				    [
				        "icon-star-on",
				        "&#xe90b"
				    ],
				    [
				        "icon-heart-on",
				        "&#xe90c"
				    ]
				];
		$data = array();
		for ($i=0; $i < count($icons); $i++) { 
			if ($html) {
				$data['feather '.$icons[$i][0]] = '<i class="feather '.$icons[$i][0].'"></i>';
			} else {
				$data['feather '.$icons[$i][0]] = $icons[$i][0];
			}
		}
		return $data;
	}

	private function set($value='')
	{
		$string = '.icon-alert-octagon:before { content: "\e81b"; }.icon-alert-circle:before { content: "\e81c"; }.icon-activity:before { content: "\e81d"; }.icon-alert-triangle:before { content: "\e81e"; }.icon-align-center:before { content: "\e81f"; }.icon-airplay:before { content: "\e820"; }.icon-align-justify:before { content: "\e821"; }.icon-align-left:before { content: "\e822"; }.icon-align-right:before { content: "\e823"; }.icon-arrow-down-left:before { content: "\e824"; }.icon-arrow-down-right:before { content: "\e825"; }.icon-anchor:before { content: "\e826"; }.icon-aperture:before { content: "\e827"; }.icon-arrow-left:before { content: "\e828"; }.icon-arrow-right:before { content: "\e829"; }.icon-arrow-down:before { content: "\e82a"; }.icon-arrow-up-left:before { content: "\e82b"; }.icon-arrow-up-right:before { content: "\e82c"; }.icon-arrow-up:before { content: "\e82d"; }.icon-award:before { content: "\e82e"; }.icon-bar-chart:before { content: "\e82f"; }.icon-at-sign:before { content: "\e830"; }.icon-bar-chart-2:before { content: "\e831"; }.icon-battery-charging:before { content: "\e832"; }.icon-bell-off:before { content: "\e833"; }.icon-battery:before { content: "\e834"; }.icon-bluetooth:before { content: "\e835"; }.icon-bell:before { content: "\e836"; }.icon-book:before { content: "\e837"; }.icon-briefcase:before { content: "\e838"; }.icon-camera-off:before { content: "\e839"; }.icon-calendar:before { content: "\e83a"; }.icon-bookmark:before { content: "\e83b"; }.icon-box:before { content: "\e83c"; }.icon-camera:before { content: "\e83d"; }.icon-check-circle:before { content: "\e83e"; }.icon-check:before { content: "\e83f"; }.icon-check-square:before { content: "\e840"; }.icon-cast:before { content: "\e841"; }.icon-chevron-down:before { content: "\e842"; }.icon-chevron-left:before { content: "\e843"; }.icon-chevron-right:before { content: "\e844"; }.icon-chevron-up:before { content: "\e845"; }.icon-chevrons-down:before { content: "\e846"; }.icon-chevrons-right:before { content: "\e847"; }.icon-chevrons-up:before { content: "\e848"; }.icon-chevrons-left:before { content: "\e849"; }.icon-circle:before { content: "\e84a"; }.icon-clipboard:before { content: "\e84b"; }.icon-chrome:before { content: "\e84c"; }.icon-clock:before { content: "\e84d"; }.icon-cloud-lightning:before { content: "\e84e"; }.icon-cloud-drizzle:before { content: "\e84f"; }.icon-cloud-rain:before { content: "\e850"; }.icon-cloud-off:before { content: "\e851"; }.icon-codepen:before { content: "\e852"; }.icon-cloud-snow:before { content: "\e853"; }.icon-compass:before { content: "\e854"; }.icon-copy:before { content: "\e855"; }.icon-corner-down-right:before { content: "\e856"; }.icon-corner-down-left:before { content: "\e857"; }.icon-corner-left-down:before { content: "\e858"; }.icon-corner-left-up:before { content: "\e859"; }.icon-corner-up-left:before { content: "\e85a"; }.icon-corner-up-right:before { content: "\e85b"; }.icon-corner-right-down:before { content: "\e85c"; }.icon-corner-right-up:before { content: "\e85d"; }.icon-cpu:before { content: "\e85e"; }.icon-credit-card:before { content: "\e85f"; }.icon-crosshair:before { content: "\e860"; }.icon-disc:before { content: "\e861"; }.icon-delete:before { content: "\e862"; }.icon-download-cloud:before { content: "\e863"; }.icon-download:before { content: "\e864"; }.icon-droplet:before { content: "\e865"; }.icon-edit-2:before { content: "\e866"; }.icon-edit:before { content: "\e867"; }.icon-edit-1:before { content: "\e868"; }.icon-external-link:before { content: "\e869"; }.icon-eye:before { content: "\e86a"; }.icon-feather:before { content: "\e86b"; }.icon-facebook:before { content: "\e86c"; }.icon-file-minus:before { content: "\e86d"; }.icon-eye-off:before { content: "\e86e"; }.icon-fast-forward:before { content: "\e86f"; }.icon-file-text:before { content: "\e870"; }.icon-film:before { content: "\e871"; }.icon-file:before { content: "\e872"; }.icon-file-plus:before { content: "\e873"; }.icon-folder:before { content: "\e874"; }.icon-filter:before { content: "\e875"; }.icon-flag:before { content: "\e876"; }.icon-globe:before { content: "\e877"; }.icon-grid:before { content: "\e878"; }.icon-heart:before { content: "\e879"; }.icon-home:before { content: "\e87a"; }.icon-github:before { content: "\e87b"; }.icon-image:before { content: "\e87c"; }.icon-inbox:before { content: "\e87d"; }.icon-layers:before { content: "\e87e"; }.icon-info:before { content: "\e87f"; }.icon-instagram:before { content: "\e880"; }.icon-layout:before { content: "\e881"; }.icon-link-2:before { content: "\e882"; }.icon-life-buoy:before { content: "\e883"; }.icon-link:before { content: "\e884"; }.icon-log-in:before { content: "\e885"; }.icon-list:before { content: "\e886"; }.icon-lock:before { content: "\e887"; }.icon-log-out:before { content: "\e888"; }.icon-loader:before { content: "\e889"; }.icon-mail:before { content: "\e88a"; }.icon-maximize-2:before { content: "\e88b"; }.icon-map:before { content: "\e88c"; }.icon-map-pin:before { content: "\e88e"; }.icon-menu:before { content: "\e88f"; }.icon-message-circle:before { content: "\e890"; }.icon-message-square:before { content: "\e891"; }.icon-minimize-2:before { content: "\e892"; }.icon-mic-off:before { content: "\e893"; }.icon-minus-circle:before { content: "\e894"; }.icon-mic:before { content: "\e895"; }.icon-minus-square:before { content: "\e896"; }.icon-minus:before { content: "\e897"; }.icon-moon:before { content: "\e898"; }.icon-monitor:before { content: "\e899"; }.icon-more-vertical:before { content: "\e89a"; }.icon-more-horizontal:before { content: "\e89b"; }.icon-move:before { content: "\e89c"; }.icon-music:before { content: "\e89d"; }.icon-navigation-2:before { content: "\e89e"; }.icon-navigation:before { content: "\e89f"; }.icon-octagon:before { content: "\e8a0"; }.icon-package:before { content: "\e8a1"; }.icon-pause-circle:before { content: "\e8a2"; }.icon-pause:before { content: "\e8a3"; }.icon-percent:before { content: "\e8a4"; }.icon-phone-call:before { content: "\e8a5"; }.icon-phone-forwarded:before { content: "\e8a6"; }.icon-phone-missed:before { content: "\e8a7"; }.icon-phone-off:before { content: "\e8a8"; }.icon-phone-incoming:before { content: "\e8a9"; }.icon-phone:before { content: "\e8aa"; }.icon-phone-outgoing:before { content: "\e8ab"; }.icon-pie-chart:before { content: "\e8ac"; }.icon-play-circle:before { content: "\e8ad"; }.icon-play:before { content: "\e8ae"; }.icon-plus-square:before { content: "\e8af"; }.icon-plus-circle:before { content: "\e8b0"; }.icon-plus:before { content: "\e8b1"; }.icon-pocket:before { content: "\e8b2"; }.icon-printer:before { content: "\e8b3"; }.icon-power:before { content: "\e8b4"; }.icon-radio:before { content: "\e8b5"; }.icon-repeat:before { content: "\e8b6"; }.icon-refresh-ccw:before { content: "\e8b7"; }.icon-rewind:before { content: "\e8b8"; }.icon-rotate-ccw:before { content: "\e8b9"; }.icon-refresh-cw:before { content: "\e8ba"; }.icon-rotate-cw:before { content: "\e8bb"; }.icon-save:before { content: "\e8bc"; }.icon-search:before { content: "\e8bd"; }.icon-server:before { content: "\e8be"; }.icon-scissors:before { content: "\e8bf"; }.icon-share-2:before { content: "\e8c0"; }.icon-share:before { content: "\e8c1"; }.icon-shield:before { content: "\e8c2"; }.icon-settings:before { content: "\e8c3"; }.icon-skip-back:before { content: "\e8c4"; }.icon-shuffle:before { content: "\e8c5"; }.icon-sidebar:before { content: "\e8c6"; }.icon-skip-forward:before { content: "\e8c7"; }.icon-slack:before { content: "\e8c8"; }.icon-slash:before { content: "\e8c9"; }.icon-smartphone:before { content: "\e8ca"; }.icon-square:before { content: "\e8cb"; }.icon-speaker:before { content: "\e8cc"; }.icon-star:before { content: "\e8cd"; }.icon-stop-circle:before { content: "\e8ce"; }.icon-sun:before { content: "\e8cf"; }.icon-sunrise:before { content: "\e8d0"; }.icon-tablet:before { content: "\e8d1"; }.icon-tag:before { content: "\e8d2"; }.icon-sunset:before { content: "\e8d3"; }.icon-target:before { content: "\e8d4"; }.icon-thermometer:before { content: "\e8d5"; }.icon-thumbs-up:before { content: "\e8d6"; }.icon-thumbs-down:before { content: "\e8d7"; }.icon-toggle-left:before { content: "\e8d8"; }.icon-toggle-right:before { content: "\e8d9"; }.icon-trash-2:before { content: "\e8da"; }.icon-trash:before { content: "\e8db"; }.icon-trending-up:before { content: "\e8dc"; }.icon-trending-down:before { content: "\e8dd"; }.icon-triangle:before { content: "\e8de"; }.icon-type:before { content: "\e8df"; }.icon-twitter:before { content: "\e8e0"; }.icon-upload:before { content: "\e8e1"; }.icon-umbrella:before { content: "\e8e2"; }.icon-upload-cloud:before { content: "\e8e3"; }.icon-unlock:before { content: "\e8e4"; }.icon-user-check:before { content: "\e8e5"; }.icon-user-minus:before { content: "\e8e6"; }.icon-user-plus:before { content: "\e8e7"; }.icon-user-x:before { content: "\e8e8"; }.icon-user:before { content: "\e8e9"; }.icon-users:before { content: "\e8ea"; }.icon-video-off:before { content: "\e8eb"; }.icon-video:before { content: "\e8ec"; }.icon-voicemail:before { content: "\e8ed"; }.icon-volume-x:before { content: "\e8ee"; }.icon-volume-2:before { content: "\e8ef"; }.icon-volume-1:before { content: "\e8f0"; }.icon-volume:before { content: "\e8f1"; }.icon-watch:before { content: "\e8f2"; }.icon-wifi:before { content: "\e8f3"; }.icon-x-square:before { content: "\e8f4"; }.icon-wind:before { content: "\e8f5"; }.icon-x:before { content: "\e8f6"; }.icon-x-circle:before { content: "\e8f7"; }.icon-zap:before { content: "\e8f8"; }.icon-zoom-in:before { content: "\e8f9"; }.icon-zoom-out:before { content: "\e8fa"; }.icon-command:before { content: "\e8fb"; }.icon-cloud:before { content: "\e8fc"; }.icon-hash:before { content: "\e8fd"; }.icon-headphones:before { content: "\e8fe"; }.icon-underline:before { content: "\e8ff"; }.icon-italic:before { content: "\e900"; }.icon-bold:before { content: "\e901"; }.icon-crop:before { content: "\e902"; }.icon-help-circle:before { content: "\e903"; }.icon-paperclip:before { content: "\e904"; }.icon-shopping-cart:before { content: "\e905"; }.icon-tv:before { content: "\e906"; }.icon-wifi-off:before { content: "\e907"; }.icon-minimize:before { content: "\e88d"; }.icon-maximize:before { content: "\e908"; }.icon-gitlab:before { content: "\e909"; }.icon-sliders:before { content: "\e90a"; }.icon-star-on:before { content: "\e90b"; }.icon-heart-on:before { content: "\e90c"; }';
			$strings = preg_replace('/"; }/', '', $string);
			$strings = str_replace('\\', '&#x', $strings);
			$icons = preg_split('/\./', $strings);
			for ($i=0; $i < count($icons); $i++) { 
				$data[$i] = preg_split('/:before { content: "/', $icons[$i]);
			}
	}
}